### ISSUE TITLE
Editing base.html and index.html

### ISSUE THREAD

**Issue by JonHilton** [lorin/mezzanine-paas#1]
Thanks very much for setting this up, it has worked really well.

I'd like to edit the templates, where is this install looking for them?

Also, I don't need Cartridge, who can I remove it?

Thanks.

**Comment by lorin** [comment]
The [base.html](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/templates/base.html) and [index.html](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/templates/base.html) templates reside in the mezzanine Python package. You'll want to provide your own versions of these files if you want to override them. If you want to extend these rather than completely override them, I believe you need to use the "overextends" template tag for this, check out [Overriding vs Extending Templates](http://mezzanine.jupo.org/docs/content-architecture.html).

I believe you'll need to create a `mezzanine_heroku/templates` directory and put the template files in there.

If you don't need Cartridge
- remove the Cartridge package from `requirements.txt`
- remove references to cartridge in `mezzanine_heroku/settings.py`
- remove cartridge-related urls from `mezzanine_heroku/urls.py`
